In [16]:
import numpy as np
import torch
import tqdm
from torch.utils.data import Dataset
from matplotlib import pyplot as plt
from widis_lstm_tools.nn import LSTMLayer


In [18]:
??LSTMLayer

In [6]:
b=np.random.rand(4,4)

In [7]:
[a,b]

[array([[0.83201829, 0.55431286, 0.86562911, 0.77977198],
        [0.62561938, 0.65966294, 0.62319033, 0.35048853],
        [0.31482263, 0.14404961, 0.6100838 , 0.02468585]]),
 array([[0.42734281, 0.66012537, 0.8651542 , 0.12049186],
        [0.58234101, 0.27885603, 0.55071015, 0.83639998],
        [0.02239193, 0.59531778, 0.5665424 , 0.66544935],
        [0.44866059, 0.21168179, 0.35118498, 0.53156995]])]

In [8]:
import torch

In [13]:
w = torch.empty(3, 5)

In [14]:
print(w)

torch.nn.init.xavier_normal_(w)

tensor([[ 1.2673e+24,  4.5775e-41,  6.9914e-30,  3.0707e-41, -8.7464e-02],
        [-7.7289e-01,  1.4127e-01,  2.5834e-01,  2.8241e-01, -1.5280e-01],
        [-4.1757e-01,  6.6509e-01,  1.2614e-01, -3.3438e-02, -1.0911e+00]])


tensor([[ 0.4116,  0.4061, -0.1701,  0.2744, -0.0892],
        [-0.4817,  0.4289,  0.0791,  0.2528,  1.0192],
        [-0.1382, -0.0668, -0.3246, -0.0412,  0.1588]])

In [15]:
w.sum()

tensor(1.7191)